# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RunContentPd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webtype', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7f51\u7ad9\u7c7b\u578b')),
                ('url', models.CharField(max_length=255, verbose_name='\u6a21\u7248\u7279\u5f81URL')),
                ('domains', models.CharField(max_length=255, verbose_name='domains')),
                ('author', models.CharField(max_length=255, verbose_name='\u6a21\u677f\u4f5c\u8005')),
                ('mysql', models.CharField(max_length=255, verbose_name='SQL\u5730\u5740')),
                ('prot', models.CharField(max_length=255, verbose_name='\u7aef\u53e3\u53f7')),
                ('username', models.CharField(max_length=255, verbose_name='\u7528\u6237\u540d')),
                ('passwd', models.CharField(max_length=255, verbose_name='\u5bc6\u7801')),
                ('database', models.CharField(max_length=255, verbose_name='\u5e93\u540d')),
                ('table', models.CharField(max_length=255, verbose_name='\u8868\u660e')),
                ('select_url', models.TextField(default='', verbose_name='\u68c0\u7d22\u6837\u5f0f')),
                ('url_xpath', models.CharField(max_length=255, verbose_name='URL\u68c0\u7d22\u8868\u8fbe\u5f0f')),
                ('url_regex', models.CharField(max_length=255, verbose_name='URL\u6b63\u5219')),
            ],
        ),
        migrations.CreateModel(
            name='RunPdDemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7f51\u7ad9\u540d')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('domains', models.CharField(max_length=255, verbose_name='domains')),
                ('author', models.CharField(max_length=255, verbose_name='\u6a21\u677f\u4f5c\u8005')),
                ('mysql', models.CharField(max_length=255, verbose_name='SQL\u5730\u5740')),
                ('prot', models.CharField(max_length=255, verbose_name='\u7aef\u53e3\u53f7')),
                ('username', models.CharField(max_length=255, verbose_name='\u7528\u6237\u540d')),
                ('passwd', models.CharField(max_length=255, verbose_name='\u5bc6\u7801')),
                ('database', models.CharField(max_length=255, verbose_name='\u5e93\u540d')),
                ('table', models.CharField(max_length=255, verbose_name='\u8868\u660e')),
                ('select_title', models.TextField(default='', verbose_name='\u68c0\u7d22\u6837\u5f0f')),
                ('title_xpath', models.CharField(max_length=255, verbose_name='\u6807\u9898\u68c0\u7d22\u8868\u8fbe\u5f0f')),
                ('title_regex', models.CharField(max_length=255, verbose_name='\u6807\u9898\u6b63\u5219')),
                ('select_url', models.TextField(default='', verbose_name='\u68c0\u7d22\u6837\u5f0f')),
                ('url_xpath', models.CharField(max_length=255, verbose_name='URL\u68c0\u7d22\u8868\u8fbe\u5f0f')),
                ('url_regex', models.CharField(max_length=255, verbose_name='URL\u6b63\u5219')),
            ],
        ),
    ]
