# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0004_auto_20160202_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rundemoconfig',
            name='select_author',
            field=models.CharField(max_length=255, verbose_name='\u68c0\u7d22\u6837\u5f0f'),
        ),
        migrations.AlterField(
            model_name='rundemoconfig',
            name='select_comment',
            field=models.CharField(max_length=255, verbose_name='\u68c0\u7d22\u6837\u5f0f'),
        ),
        migrations.AlterField(
            model_name='rundemoconfig',
            name='select_content',
            field=models.CharField(max_length=255, verbose_name='\u68c0\u7d22\u6837\u5f0f'),
        ),
        migrations.AlterField(
            model_name='rundemoconfig',
            name='select_date',
            field=models.CharField(max_length=255, verbose_name='\u68c0\u7d22\u6837\u5f0f'),
        ),
        migrations.AlterField(
            model_name='rundemoconfig',
            name='select_ll',
            field=models.CharField(max_length=255, verbose_name='\u68c0\u7d22\u6837\u5f0f'),
        ),
        migrations.AlterField(
            model_name='rundemoconfig',
            name='select_sitename',
            field=models.CharField(max_length=255, verbose_name='\u68c0\u7d22\u6837\u5f0f'),
        ),
        migrations.AlterField(
            model_name='rundemoconfig',
            name='select_title',
            field=models.CharField(max_length=255, verbose_name='\u68c0\u7d22\u6837\u5f0f'),
        ),
        migrations.AlterField(
            model_name='rundemoconfig',
            name='select_url',
            field=models.CharField(max_length=255, verbose_name='\u68c0\u7d22\u6837\u5f0f'),
        ),
        migrations.AlterField(
            model_name='rundemoconfig',
            name='select_zf',
            field=models.CharField(max_length=255, verbose_name='\u68c0\u7d22\u6837\u5f0f'),
        ),
    ]
